apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simplecloud-role
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
    apiGroups:
      - ''
      - apps
    resources:
      - pods
      - pods/log
      - pods/status
      - pods/exec
      - services
      - secrets
      - configmaps
      - persistentvolumes
      - persistentvolumeclaims
      - serviceaccounts
      - deployments
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings